djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweetapp.urls')),
    path('', include('django.contrib.auth.urls'))
]

djangotweet/tweetapp/urls.py
from django.urls import path
from . import views

app_name='tweetapp'

urlpatterns = [
    path('',views.listtweet,name='listtweet'), # atilsamancioglu.com/tweetapp/
    path('addtweet/',views.addtweet,name='addtweet'), # atilsamancioglu.com/tweetapp/addtweet/
    path('addtweetbyform',views.addtweetbyform,name='addtweetbyform'),
    path('addtweetbymodelform',views.addtweetbymodelform,name='addtweetbymodelform'),
    path('signup/',views.SignUpView.as_view(),name='signup'), # Fonksiyon bazlı değil sınıf bazlı ondan as_view koyduk.
    path('deletetweet/<int:id>',views.deletetweet,name='deletetweet'),  # <int:id> list tweette alınıyor zaten (<a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>)



]

djangotweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweet(models.Model):
    # nickname=models.CharField(max_length=50)
    username=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    message=models.CharField(max_length=100)

    def __str__(self):
        return f"Tweet user: {self.username} message: {self.message}" # Admin panelinde böyle görünür.

djangotweet/tweetapp/forms.py
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet

class AddTweetForm(forms.Form):
    nickname_input=forms.CharField(label="Nickname",max_length=10)
    message_input=forms.CharField(label="Message",max_length=100,
                widget=forms.Textarea(attrs={"class":"tweetmessage"}))
                # Css dosyasında tweetmessage adında bir fonksiyon var bu
                # bu görünüümün özelliklerini belirliyor.


class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ["username","message"]

djangotweet/tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse,reverse_lazy
from tweetapp.forms import AddTweetForm,AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
# Create your views here.

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets":all_tweets}
    return render(request,'tweetapp/listtweet.html',context=tweet_dict)

@login_required(login_url="/login") # Kullanucu login değilse login sayfasına yönlendirir.
def addtweet(request):
    if request.POST:
        # HTTP POST isteği, genellikle kullanıcının bir form doldurduğu ve bu formdaki bilgilerin 
        # bir sunucuya gönderildiği durumları temsil eder. Django'da, .post metodu ile kullanıcının girdiği 
        # verilere erişebilir ve bu verileri veritabanına kaydedebilirsiniz.
        # nickname=request.POST['nickname']
        message=request.POST['message']
        models.Tweet.objects.create(username=request.user,message=message)
        return redirect(reverse('tweetapp:listtweet')) 
        # Tweet'i kaydet dedikten sonra listtweet sayfasına yönlendirir.

    else:
        return render(request,'tweetapp/addtweet.html')


def addtweetbyform(request): # Yukardakinin aynısını django form ile burda yaptık.
    # Böyle kontrolleri html içinde kendimiz yazmamıza gerek yok hataları falan kendisi ele alıyor.
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweetapp:listtweet'))

        else:
            print("error")
            return render(request,'tweetapp/addtweetbyform.html', context={"form":form})

    else:
        form = AddTweetForm()
        return render(request,'tweetapp/addtweetbyform.html',context={"form":form})


def addtweetbymodelform(request):

    if request.method == "POST":
        form = AddTweetModelForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname"]
            message = form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweetapp:listtweet'))

        else:
            print("error")
            return render(request,'tweetapp/addtweetbymodelform.html', context={"form":form})

    else:
        form = AddTweetModelForm()
        return render(request,'tweetapp/addtweetbymodelform.html',context={"form":form})

@login_required
def deletetweet(request,id):
    tweet=models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect('tweetapp:listtweet')

        
class SignUpView(CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy("login")
    template_name="registration/signup.html" 

       

djangotweet/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Tweet App</title>
    <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">
</head>
<body>

        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">Tweet App</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
                      </li>

                      <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweetapp:addtweetbyform' %}">Add Tweet By Form</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'tweetapp:addtweetbymodelform' %}">Add Tweet By Model Form</a>
                      </li> -->
                      
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a> <!-- tweetapp: dememe sebebimiz dosyanın tweetapp altında değil her app erişsin diye direk projede oluşturmamız. -->
                      </li>

                      <li class="nav-item"><form action="{% url 'logout' %}?next=/" method="post">{% csrf_token %}<button type="submit" class="nav-link btn btn-link">Logout</button></form>
                      </li>

                      <li class="nav-item"><form action="{% url 'tweetapp:signup' %}" method="post">{% csrf_token %}<button type="submit" class="nav-link btn btn-link">Signup</button></form>
                      </li>
                    </ul>
                    
                  </div>
                </div>
              </nav>
    {% block content %}


    {% endblock %}
</body>
</html>

djangotweet/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{% block content %}


<form action="" method="POST">
         {% csrf_token %}

         <div class="container" style="width:50%;">
        <!-- <div class="mb-3">
          <label for="nickname" class="form-label">Nickname</label>
          <input type="text" class="form-control" id="nickname" name="nickname">
          <div id="emailHelp" class="form-text"></div>
        </div> -->
        <div class="mb-3">
          <label for="message" class="form-label">Password</label>
          <input type="text" class="form-control" id="message" name="message">
        </div>
        
        <button type="submit" class="btn btn-primary">Send Tweet</button>
      </div>
      </form>
{% endblock %}

djangotweet/tweetapp/templates/tweetapp/addtweetbyform.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>addtweetByForm page</h1>

<div class="container tweetform">

<form action="" method="POST">
         {% csrf_token %}
       
        {% for field in form %}
        <div class="form-control">

            {{field.label_tag}}
            {{field}}

        </div>
        {% endfor %}
        <!-- <div class="mb-3">
             {{form.as_p}} Alt alta gösterir 

             {{form.nickname_input.label_tag}}
            {{form.nickname_input}}
            <br>
            {{form.message_input.label_tag}}
            {{form.message_input}}   böylelikle görünümleri kendimiz yaparız 
          </div> -->

        <button type="submit" class="btn btn-primary">Send Tweet</button>


      </form>
    </div>
{% endblock %}

djangotweet/tweetapp/templates/tweetapp/addtweetbymodelform.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>addtweetByModelForm page</h1>

<div class="container tweetform">

    <form action="" method="POST">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-control">

            {{field.label_tag}}
            {{field}}

        </div>
        {% endfor %}
        <!-- <div class="mb-3">
                 {{form.as_p}} Alt alta gösterir 
    
                 {{form.nickname_input.label_tag}}
                {{form.nickname_input}}
                <br>
                {{form.message_input.label_tag}}
                {{form.message_input}}   böylelikle görünümleri kendimiz yaparız 
              </div> -->

        <button type="submit" class="btn btn-primary">Send Tweet</button>


    </form>
</div {% endblock %}

djangotweet/tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}


{% block content %}



<div class="container" style="width: 50%;">
    {%for tweet in tweets%}

    <div class="card" style="padding:10px;">

        <div class="card-header" style="background-color: rgb(111, 111, 233);">


            <h4>{{tweet.username}}</h4>

        </div>

    
        <div class="card-body">

            <p class="card-text">{{tweet.message}}

            </p>


        </div>

        {% if tweet.username == user %}
        <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </div>
    <!-- {{tweet.nickname}}
     .nickname demeseydik def __str__(self):
            return f"Tweet nick: {self.nickname} message: {self.message}" bu formatta görünücekti. --> -->


{%endfor%}


</div>
{%endblock%}
</div>